---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn install
      - name: Run yarn start
        run: yarn start &
      - name: Set env
        run: echo "ESLINT_USE_FLAT_CONFIG=false" >> $GITHUB_ENV
      - name: Echo ESLINT_USE_FLAT_CONFIG
        run: echo $ESLINT_USE_FLAT_CONFIG
      - name: Run yarn lint
        run: yarn lint
      - name: Run yarn test
        run: yarn test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image     
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: thibovdb256/webapp:latest
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}