---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn install
      - run: yarn add eslint@latest
      - name: Run yarn lint
        run: yarn lint        